/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CChainSharedAssetBalance;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * CChainAtomicBalances
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class CChainAtomicBalances {
  @SerializedName("atomicMemoryUnlocked")
  private List<CChainSharedAssetBalance> atomicMemoryUnlocked = new ArrayList<CChainSharedAssetBalance>();

  @SerializedName("atomicMemoryLocked")
  private List<CChainSharedAssetBalance> atomicMemoryLocked = new ArrayList<CChainSharedAssetBalance>();

  public CChainAtomicBalances atomicMemoryUnlocked(List<CChainSharedAssetBalance> atomicMemoryUnlocked) {
    this.atomicMemoryUnlocked = atomicMemoryUnlocked;
    return this;
  }

  public CChainAtomicBalances addAtomicMemoryUnlockedItem(CChainSharedAssetBalance atomicMemoryUnlockedItem) {
    this.atomicMemoryUnlocked.add(atomicMemoryUnlockedItem);
    return this;
  }

   /**
   * Get atomicMemoryUnlocked
   * @return atomicMemoryUnlocked
  **/
  @Schema(required = true, description = "")
  public List<CChainSharedAssetBalance> getAtomicMemoryUnlocked() {
    return atomicMemoryUnlocked;
  }

  public void setAtomicMemoryUnlocked(List<CChainSharedAssetBalance> atomicMemoryUnlocked) {
    this.atomicMemoryUnlocked = atomicMemoryUnlocked;
  }

  public CChainAtomicBalances atomicMemoryLocked(List<CChainSharedAssetBalance> atomicMemoryLocked) {
    this.atomicMemoryLocked = atomicMemoryLocked;
    return this;
  }

  public CChainAtomicBalances addAtomicMemoryLockedItem(CChainSharedAssetBalance atomicMemoryLockedItem) {
    this.atomicMemoryLocked.add(atomicMemoryLockedItem);
    return this;
  }

   /**
   * Get atomicMemoryLocked
   * @return atomicMemoryLocked
  **/
  @Schema(required = true, description = "")
  public List<CChainSharedAssetBalance> getAtomicMemoryLocked() {
    return atomicMemoryLocked;
  }

  public void setAtomicMemoryLocked(List<CChainSharedAssetBalance> atomicMemoryLocked) {
    this.atomicMemoryLocked = atomicMemoryLocked;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CChainAtomicBalances cchainAtomicBalances = (CChainAtomicBalances) o;
    return Objects.equals(this.atomicMemoryUnlocked, cchainAtomicBalances.atomicMemoryUnlocked) &&
        Objects.equals(this.atomicMemoryLocked, cchainAtomicBalances.atomicMemoryLocked);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atomicMemoryUnlocked, atomicMemoryLocked);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CChainAtomicBalances {\n");
    
    sb.append("    atomicMemoryUnlocked: ").append(toIndentedString(atomicMemoryUnlocked)).append("\n");
    sb.append("    atomicMemoryLocked: ").append(toIndentedString(atomicMemoryLocked)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
