/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Asset;
import io.swagger.client.model.EVMInput;
import io.swagger.client.model.Utxo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * CChainExportTransaction
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class CChainExportTransaction implements InlineResponse2001, AnyOfListCChainAtomicTransactionsResponseTransactionsItems {
  @SerializedName("txHash")
  private String txHash = null;

  @SerializedName("blockHeight")
  private BigDecimal blockHeight = null;

  @SerializedName("blockHash")
  private String blockHash = null;

  @SerializedName("timestamp")
  private BigDecimal timestamp = null;

  @SerializedName("memo")
  private String memo = null;

  @SerializedName("amountUnlocked")
  private List<Asset> amountUnlocked = new ArrayList<Asset>();

  @SerializedName("amountCreated")
  private List<Asset> amountCreated = new ArrayList<Asset>();

  @SerializedName("sourceChain")
  private String sourceChain = null;

  @SerializedName("destinationChain")
  private String destinationChain = null;

  /**
   * Type of transaction.
   */
  @JsonAdapter(TxTypeEnum.Adapter.class)
  public enum TxTypeEnum {
    EXPORTTX("ExportTx");

    private String value;

    TxTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static TxTypeEnum fromValue(String input) {
      for (TxTypeEnum b : TxTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<TxTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TxTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public TxTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return TxTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("txType")
  private TxTypeEnum txType = null;

  @SerializedName("evmInputs")
  private List<EVMInput> evmInputs = new ArrayList<EVMInput>();

  @SerializedName("emittedUtxos")
  private List<Utxo> emittedUtxos = new ArrayList<Utxo>();

  public CChainExportTransaction txHash(String txHash) {
    this.txHash = txHash;
    return this;
  }

   /**
   * Unique ID for this transaction.
   * @return txHash
  **/
  @Schema(example = "3j9JpF1aGuQtLLbo3YkvvKkWrCZViXZjdeJQWUSEY5hcqUn2c", required = true, description = "Unique ID for this transaction.")
  public String getTxHash() {
    return txHash;
  }

  public void setTxHash(String txHash) {
    this.txHash = txHash;
  }

  public CChainExportTransaction blockHeight(BigDecimal blockHeight) {
    this.blockHeight = blockHeight;
    return this;
  }

   /**
   * Height of the block this transaction belongs to.
   * @return blockHeight
  **/
  @Schema(example = "1005", required = true, description = "Height of the block this transaction belongs to.")
  public BigDecimal getBlockHeight() {
    return blockHeight;
  }

  public void setBlockHeight(BigDecimal blockHeight) {
    this.blockHeight = blockHeight;
  }

  public CChainExportTransaction blockHash(String blockHash) {
    this.blockHash = blockHash;
    return this;
  }

   /**
   * Hash of the block this transaction belongs to.
   * @return blockHash
  **/
  @Schema(example = "0x57a5cb7704561d1d59bd563b6421021b7563960c05ba3ae0e36fc36917c742ee", required = true, description = "Hash of the block this transaction belongs to.")
  public String getBlockHash() {
    return blockHash;
  }

  public void setBlockHash(String blockHash) {
    this.blockHash = blockHash;
  }

  public CChainExportTransaction timestamp(BigDecimal timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Latest timestamp in seconds this transaction was accepted.
   * @return timestamp
  **/
  @Schema(example = "1600762738", required = true, description = "Latest timestamp in seconds this transaction was accepted.")
  public BigDecimal getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(BigDecimal timestamp) {
    this.timestamp = timestamp;
  }

  public CChainExportTransaction memo(String memo) {
    this.memo = memo;
    return this;
  }

   /**
   * Hex encoded memo bytes for this transaction.
   * @return memo
  **/
  @Schema(example = "0x546865204176616c616e6368652050726f6a656374", required = true, description = "Hex encoded memo bytes for this transaction.")
  public String getMemo() {
    return memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  public CChainExportTransaction amountUnlocked(List<Asset> amountUnlocked) {
    this.amountUnlocked = amountUnlocked;
    return this;
  }

  public CChainExportTransaction addAmountUnlockedItem(Asset amountUnlockedItem) {
    this.amountUnlocked.add(amountUnlockedItem);
    return this;
  }

   /**
   * Assets unlocked by inputs of this transaction.
   * @return amountUnlocked
  **/
  @Schema(required = true, description = "Assets unlocked by inputs of this transaction.")
  public List<Asset> getAmountUnlocked() {
    return amountUnlocked;
  }

  public void setAmountUnlocked(List<Asset> amountUnlocked) {
    this.amountUnlocked = amountUnlocked;
  }

  public CChainExportTransaction amountCreated(List<Asset> amountCreated) {
    this.amountCreated = amountCreated;
    return this;
  }

  public CChainExportTransaction addAmountCreatedItem(Asset amountCreatedItem) {
    this.amountCreated.add(amountCreatedItem);
    return this;
  }

   /**
   * Assets created by outputs of this transaction.
   * @return amountCreated
  **/
  @Schema(required = true, description = "Assets created by outputs of this transaction.")
  public List<Asset> getAmountCreated() {
    return amountCreated;
  }

  public void setAmountCreated(List<Asset> amountCreated) {
    this.amountCreated = amountCreated;
  }

  public CChainExportTransaction sourceChain(String sourceChain) {
    this.sourceChain = sourceChain;
    return this;
  }

   /**
   * Source chain for an atomic transaction.
   * @return sourceChain
  **/
  @Schema(example = "2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM", required = true, description = "Source chain for an atomic transaction.")
  public String getSourceChain() {
    return sourceChain;
  }

  public void setSourceChain(String sourceChain) {
    this.sourceChain = sourceChain;
  }

  public CChainExportTransaction destinationChain(String destinationChain) {
    this.destinationChain = destinationChain;
    return this;
  }

   /**
   * Destination chain for an atomic transaction.
   * @return destinationChain
  **/
  @Schema(example = "2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM", required = true, description = "Destination chain for an atomic transaction.")
  public String getDestinationChain() {
    return destinationChain;
  }

  public void setDestinationChain(String destinationChain) {
    this.destinationChain = destinationChain;
  }

  public CChainExportTransaction txType(TxTypeEnum txType) {
    this.txType = txType;
    return this;
  }

   /**
   * Type of transaction.
   * @return txType
  **/
  @Schema(example = "ExportTx", required = true, description = "Type of transaction.")
  public TxTypeEnum getTxType() {
    return txType;
  }

  public void setTxType(TxTypeEnum txType) {
    this.txType = txType;
  }

  public CChainExportTransaction evmInputs(List<EVMInput> evmInputs) {
    this.evmInputs = evmInputs;
    return this;
  }

  public CChainExportTransaction addEvmInputsItem(EVMInput evmInputsItem) {
    this.evmInputs.add(evmInputsItem);
    return this;
  }

   /**
   * Get evmInputs
   * @return evmInputs
  **/
  @Schema(required = true, description = "")
  public List<EVMInput> getEvmInputs() {
    return evmInputs;
  }

  public void setEvmInputs(List<EVMInput> evmInputs) {
    this.evmInputs = evmInputs;
  }

  public CChainExportTransaction emittedUtxos(List<Utxo> emittedUtxos) {
    this.emittedUtxos = emittedUtxos;
    return this;
  }

  public CChainExportTransaction addEmittedUtxosItem(Utxo emittedUtxosItem) {
    this.emittedUtxos.add(emittedUtxosItem);
    return this;
  }

   /**
   * Get emittedUtxos
   * @return emittedUtxos
  **/
  @Schema(required = true, description = "")
  public List<Utxo> getEmittedUtxos() {
    return emittedUtxos;
  }

  public void setEmittedUtxos(List<Utxo> emittedUtxos) {
    this.emittedUtxos = emittedUtxos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CChainExportTransaction cchainExportTransaction = (CChainExportTransaction) o;
    return Objects.equals(this.txHash, cchainExportTransaction.txHash) &&
        Objects.equals(this.blockHeight, cchainExportTransaction.blockHeight) &&
        Objects.equals(this.blockHash, cchainExportTransaction.blockHash) &&
        Objects.equals(this.timestamp, cchainExportTransaction.timestamp) &&
        Objects.equals(this.memo, cchainExportTransaction.memo) &&
        Objects.equals(this.amountUnlocked, cchainExportTransaction.amountUnlocked) &&
        Objects.equals(this.amountCreated, cchainExportTransaction.amountCreated) &&
        Objects.equals(this.sourceChain, cchainExportTransaction.sourceChain) &&
        Objects.equals(this.destinationChain, cchainExportTransaction.destinationChain) &&
        Objects.equals(this.txType, cchainExportTransaction.txType) &&
        Objects.equals(this.evmInputs, cchainExportTransaction.evmInputs) &&
        Objects.equals(this.emittedUtxos, cchainExportTransaction.emittedUtxos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(txHash, blockHeight, blockHash, timestamp, memo, amountUnlocked, amountCreated, sourceChain, destinationChain, txType, evmInputs, emittedUtxos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CChainExportTransaction {\n");
    
    sb.append("    txHash: ").append(toIndentedString(txHash)).append("\n");
    sb.append("    blockHeight: ").append(toIndentedString(blockHeight)).append("\n");
    sb.append("    blockHash: ").append(toIndentedString(blockHash)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
    sb.append("    amountUnlocked: ").append(toIndentedString(amountUnlocked)).append("\n");
    sb.append("    amountCreated: ").append(toIndentedString(amountCreated)).append("\n");
    sb.append("    sourceChain: ").append(toIndentedString(sourceChain)).append("\n");
    sb.append("    destinationChain: ").append(toIndentedString(destinationChain)).append("\n");
    sb.append("    txType: ").append(toIndentedString(txType)).append("\n");
    sb.append("    evmInputs: ").append(toIndentedString(evmInputs)).append("\n");
    sb.append("    emittedUtxos: ").append(toIndentedString(emittedUtxos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
