/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Erc1155Token;
import io.swagger.client.model.RichAddress;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Erc1155TransferDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class Erc1155TransferDetails {
  @SerializedName("from")
  private RichAddress from = null;

  @SerializedName("to")
  private RichAddress to = null;

  @SerializedName("value")
  private String value = null;

  @SerializedName("erc1155Token")
  private Erc1155Token erc1155Token = null;

  public Erc1155TransferDetails from(RichAddress from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  @Schema(required = true, description = "")
  public RichAddress getFrom() {
    return from;
  }

  public void setFrom(RichAddress from) {
    this.from = from;
  }

  public Erc1155TransferDetails to(RichAddress to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @Schema(required = true, description = "")
  public RichAddress getTo() {
    return to;
  }

  public void setTo(RichAddress to) {
    this.to = to;
  }

  public Erc1155TransferDetails value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(example = "10000000000000000000", required = true, description = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public Erc1155TransferDetails erc1155Token(Erc1155Token erc1155Token) {
    this.erc1155Token = erc1155Token;
    return this;
  }

   /**
   * Get erc1155Token
   * @return erc1155Token
  **/
  @Schema(required = true, description = "")
  public Erc1155Token getErc1155Token() {
    return erc1155Token;
  }

  public void setErc1155Token(Erc1155Token erc1155Token) {
    this.erc1155Token = erc1155Token;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Erc1155TransferDetails erc1155TransferDetails = (Erc1155TransferDetails) o;
    return Objects.equals(this.from, erc1155TransferDetails.from) &&
        Objects.equals(this.to, erc1155TransferDetails.to) &&
        Objects.equals(this.value, erc1155TransferDetails.value) &&
        Objects.equals(this.erc1155Token, erc1155TransferDetails.erc1155Token);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, to, value, erc1155Token);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Erc1155TransferDetails {\n");
    
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    erc1155Token: ").append(toIndentedString(erc1155Token)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
