/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * Erc20TokenBalance
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class Erc20TokenBalance {
  @SerializedName("address")
  private String address = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("decimals")
  private BigDecimal decimals = null;

  @SerializedName("logoUri")
  private String logoUri = null;

  /**
   * Gets or Sets ercType
   */
  @JsonAdapter(ErcTypeEnum.Adapter.class)
  public enum ErcTypeEnum {
    ERC_20("ERC-20");

    private String value;

    ErcTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ErcTypeEnum fromValue(String input) {
      for (ErcTypeEnum b : ErcTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ErcTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ErcTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public ErcTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return ErcTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("ercType")
  private ErcTypeEnum ercType = null;

  @SerializedName("price")
  private AllOfErc20TokenBalancePrice price = null;

  @SerializedName("chainId")
  private String chainId = null;

  @SerializedName("balance")
  private String balance = null;

  @SerializedName("balanceValue")
  private AllOfErc20TokenBalanceBalanceValue balanceValue = null;

  public Erc20TokenBalance address(String address) {
    this.address = address;
    return this;
  }

   /**
   * A wallet or contract address in mixed-case checksum encoding.
   * @return address
  **/
  @Schema(example = "0x71C7656EC7ab88b098defB751B7401B5f6d8976F", required = true, description = "A wallet or contract address in mixed-case checksum encoding.")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public Erc20TokenBalance name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The contract name.
   * @return name
  **/
  @Schema(example = "Wrapped AVAX", required = true, description = "The contract name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Erc20TokenBalance symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * The contract symbol.
   * @return symbol
  **/
  @Schema(example = "WAVAX", required = true, description = "The contract symbol.")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public Erc20TokenBalance decimals(BigDecimal decimals) {
    this.decimals = decimals;
    return this;
  }

   /**
   * The number of decimals the token uses. For example &#x60;6&#x60;,        means to divide the token amount by &#x60;1000000&#x60; to get its user        representation.
   * @return decimals
  **/
  @Schema(example = "18", required = true, description = "The number of decimals the token uses. For example `6`,        means to divide the token amount by `1000000` to get its user        representation.")
  public BigDecimal getDecimals() {
    return decimals;
  }

  public void setDecimals(BigDecimal decimals) {
    this.decimals = decimals;
  }

  public Erc20TokenBalance logoUri(String logoUri) {
    this.logoUri = logoUri;
    return this;
  }

   /**
   * The logo uri for the address.
   * @return logoUri
  **/
  @Schema(example = "https://glacier-api.avax.network/proxy/chain-assets/main/chains/43114/token-logo.png", description = "The logo uri for the address.")
  public String getLogoUri() {
    return logoUri;
  }

  public void setLogoUri(String logoUri) {
    this.logoUri = logoUri;
  }

  public Erc20TokenBalance ercType(ErcTypeEnum ercType) {
    this.ercType = ercType;
    return this;
  }

   /**
   * Get ercType
   * @return ercType
  **/
  @Schema(required = true, description = "")
  public ErcTypeEnum getErcType() {
    return ercType;
  }

  public void setErcType(ErcTypeEnum ercType) {
    this.ercType = ercType;
  }

  public Erc20TokenBalance price(AllOfErc20TokenBalancePrice price) {
    this.price = price;
    return this;
  }

   /**
   * The token price, if available.
   * @return price
  **/
  @Schema(description = "The token price, if available.")
  public AllOfErc20TokenBalancePrice getPrice() {
    return price;
  }

  public void setPrice(AllOfErc20TokenBalancePrice price) {
    this.price = price;
  }

  public Erc20TokenBalance chainId(String chainId) {
    this.chainId = chainId;
    return this;
  }

   /**
   * The evm chain id.
   * @return chainId
  **/
  @Schema(example = "43114", required = true, description = "The evm chain id.")
  public String getChainId() {
    return chainId;
  }

  public void setChainId(String chainId) {
    this.chainId = chainId;
  }

  public Erc20TokenBalance balance(String balance) {
    this.balance = balance;
    return this;
  }

   /**
   * The address balance for the token, in units specified by the        &#x60;decimals&#x60; value for the contract.
   * @return balance
  **/
  @Schema(example = "2000000000000000000", required = true, description = "The address balance for the token, in units specified by the        `decimals` value for the contract.")
  public String getBalance() {
    return balance;
  }

  public void setBalance(String balance) {
    this.balance = balance;
  }

  public Erc20TokenBalance balanceValue(AllOfErc20TokenBalanceBalanceValue balanceValue) {
    this.balanceValue = balanceValue;
    return this;
  }

   /**
   * The monetary value of the balance, if a price is available for the token.
   * @return balanceValue
  **/
  @Schema(description = "The monetary value of the balance, if a price is available for the token.")
  public AllOfErc20TokenBalanceBalanceValue getBalanceValue() {
    return balanceValue;
  }

  public void setBalanceValue(AllOfErc20TokenBalanceBalanceValue balanceValue) {
    this.balanceValue = balanceValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Erc20TokenBalance erc20TokenBalance = (Erc20TokenBalance) o;
    return Objects.equals(this.address, erc20TokenBalance.address) &&
        Objects.equals(this.name, erc20TokenBalance.name) &&
        Objects.equals(this.symbol, erc20TokenBalance.symbol) &&
        Objects.equals(this.decimals, erc20TokenBalance.decimals) &&
        Objects.equals(this.logoUri, erc20TokenBalance.logoUri) &&
        Objects.equals(this.ercType, erc20TokenBalance.ercType) &&
        Objects.equals(this.price, erc20TokenBalance.price) &&
        Objects.equals(this.chainId, erc20TokenBalance.chainId) &&
        Objects.equals(this.balance, erc20TokenBalance.balance) &&
        Objects.equals(this.balanceValue, erc20TokenBalance.balanceValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, name, symbol, decimals, logoUri, ercType, price, chainId, balance, balanceValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Erc20TokenBalance {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    decimals: ").append(toIndentedString(decimals)).append("\n");
    sb.append("    logoUri: ").append(toIndentedString(logoUri)).append("\n");
    sb.append("    ercType: ").append(toIndentedString(ercType)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    balanceValue: ").append(toIndentedString(balanceValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
