/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * GetBlockResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class GetBlockResponse {
  @SerializedName("blockNumber")
  private String blockNumber = null;

  @SerializedName("blockTimestamp")
  private BigDecimal blockTimestamp = null;

  @SerializedName("blockHash")
  private String blockHash = null;

  @SerializedName("txCount")
  private BigDecimal txCount = null;

  @SerializedName("atomicTxCount")
  private BigDecimal atomicTxCount = null;

  @SerializedName("baseFee")
  private String baseFee = null;

  @SerializedName("gasUsed")
  private String gasUsed = null;

  @SerializedName("gasLimit")
  private String gasLimit = null;

  @SerializedName("gasCost")
  private String gasCost = null;

  @SerializedName("parentHash")
  private String parentHash = null;

  @SerializedName("feesSpent")
  private String feesSpent = null;

  @SerializedName("cumulativeTransactions")
  private String cumulativeTransactions = null;

  public GetBlockResponse blockNumber(String blockNumber) {
    this.blockNumber = blockNumber;
    return this;
  }

   /**
   * The block number on the chain.
   * @return blockNumber
  **/
  @Schema(example = "339", required = true, description = "The block number on the chain.")
  public String getBlockNumber() {
    return blockNumber;
  }

  public void setBlockNumber(String blockNumber) {
    this.blockNumber = blockNumber;
  }

  public GetBlockResponse blockTimestamp(BigDecimal blockTimestamp) {
    this.blockTimestamp = blockTimestamp;
    return this;
  }

   /**
   * The block finality timestamp.
   * @return blockTimestamp
  **/
  @Schema(example = "1648672486", required = true, description = "The block finality timestamp.")
  public BigDecimal getBlockTimestamp() {
    return blockTimestamp;
  }

  public void setBlockTimestamp(BigDecimal blockTimestamp) {
    this.blockTimestamp = blockTimestamp;
  }

  public GetBlockResponse blockHash(String blockHash) {
    this.blockHash = blockHash;
    return this;
  }

   /**
   * The block hash identifier.
   * @return blockHash
  **/
  @Schema(example = "0x17533aeb5193378b9ff441d61728e7a2ebaf10f61fd5310759451627dfca2e7c", required = true, description = "The block hash identifier.")
  public String getBlockHash() {
    return blockHash;
  }

  public void setBlockHash(String blockHash) {
    this.blockHash = blockHash;
  }

  public GetBlockResponse txCount(BigDecimal txCount) {
    this.txCount = txCount;
    return this;
  }

   /**
   * The number of evm transactions in the block.
   * @return txCount
  **/
  @Schema(required = true, description = "The number of evm transactions in the block.")
  public BigDecimal getTxCount() {
    return txCount;
  }

  public void setTxCount(BigDecimal txCount) {
    this.txCount = txCount;
  }

  public GetBlockResponse atomicTxCount(BigDecimal atomicTxCount) {
    this.atomicTxCount = atomicTxCount;
    return this;
  }

   /**
   * The number of atomic transactions in the block.
   * @return atomicTxCount
  **/
  @Schema(required = true, description = "The number of atomic transactions in the block.")
  public BigDecimal getAtomicTxCount() {
    return atomicTxCount;
  }

  public void setAtomicTxCount(BigDecimal atomicTxCount) {
    this.atomicTxCount = atomicTxCount;
  }

  public GetBlockResponse baseFee(String baseFee) {
    this.baseFee = baseFee;
    return this;
  }

   /**
   * The base gas fee for a transaction to be included in the block.
   * @return baseFee
  **/
  @Schema(required = true, description = "The base gas fee for a transaction to be included in the block.")
  public String getBaseFee() {
    return baseFee;
  }

  public void setBaseFee(String baseFee) {
    this.baseFee = baseFee;
  }

  public GetBlockResponse gasUsed(String gasUsed) {
    this.gasUsed = gasUsed;
    return this;
  }

   /**
   * The gas used for transactions in the block.
   * @return gasUsed
  **/
  @Schema(required = true, description = "The gas used for transactions in the block.")
  public String getGasUsed() {
    return gasUsed;
  }

  public void setGasUsed(String gasUsed) {
    this.gasUsed = gasUsed;
  }

  public GetBlockResponse gasLimit(String gasLimit) {
    this.gasLimit = gasLimit;
    return this;
  }

   /**
   * The total gas limit set for transactions in the block.
   * @return gasLimit
  **/
  @Schema(required = true, description = "The total gas limit set for transactions in the block.")
  public String getGasLimit() {
    return gasLimit;
  }

  public void setGasLimit(String gasLimit) {
    this.gasLimit = gasLimit;
  }

  public GetBlockResponse gasCost(String gasCost) {
    this.gasCost = gasCost;
    return this;
  }

   /**
   * Get gasCost
   * @return gasCost
  **/
  @Schema(required = true, description = "")
  public String getGasCost() {
    return gasCost;
  }

  public void setGasCost(String gasCost) {
    this.gasCost = gasCost;
  }

  public GetBlockResponse parentHash(String parentHash) {
    this.parentHash = parentHash;
    return this;
  }

   /**
   * The hash of the parent block.
   * @return parentHash
  **/
  @Schema(required = true, description = "The hash of the parent block.")
  public String getParentHash() {
    return parentHash;
  }

  public void setParentHash(String parentHash) {
    this.parentHash = parentHash;
  }

  public GetBlockResponse feesSpent(String feesSpent) {
    this.feesSpent = feesSpent;
    return this;
  }

   /**
   * The amount of fees spent/burned for transactions in the block.
   * @return feesSpent
  **/
  @Schema(required = true, description = "The amount of fees spent/burned for transactions in the block.")
  public String getFeesSpent() {
    return feesSpent;
  }

  public void setFeesSpent(String feesSpent) {
    this.feesSpent = feesSpent;
  }

  public GetBlockResponse cumulativeTransactions(String cumulativeTransactions) {
    this.cumulativeTransactions = cumulativeTransactions;
    return this;
  }

   /**
   * The cumulative number of transactions for the chain including this block.
   * @return cumulativeTransactions
  **/
  @Schema(required = true, description = "The cumulative number of transactions for the chain including this block.")
  public String getCumulativeTransactions() {
    return cumulativeTransactions;
  }

  public void setCumulativeTransactions(String cumulativeTransactions) {
    this.cumulativeTransactions = cumulativeTransactions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetBlockResponse getBlockResponse = (GetBlockResponse) o;
    return Objects.equals(this.blockNumber, getBlockResponse.blockNumber) &&
        Objects.equals(this.blockTimestamp, getBlockResponse.blockTimestamp) &&
        Objects.equals(this.blockHash, getBlockResponse.blockHash) &&
        Objects.equals(this.txCount, getBlockResponse.txCount) &&
        Objects.equals(this.atomicTxCount, getBlockResponse.atomicTxCount) &&
        Objects.equals(this.baseFee, getBlockResponse.baseFee) &&
        Objects.equals(this.gasUsed, getBlockResponse.gasUsed) &&
        Objects.equals(this.gasLimit, getBlockResponse.gasLimit) &&
        Objects.equals(this.gasCost, getBlockResponse.gasCost) &&
        Objects.equals(this.parentHash, getBlockResponse.parentHash) &&
        Objects.equals(this.feesSpent, getBlockResponse.feesSpent) &&
        Objects.equals(this.cumulativeTransactions, getBlockResponse.cumulativeTransactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blockNumber, blockTimestamp, blockHash, txCount, atomicTxCount, baseFee, gasUsed, gasLimit, gasCost, parentHash, feesSpent, cumulativeTransactions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetBlockResponse {\n");
    
    sb.append("    blockNumber: ").append(toIndentedString(blockNumber)).append("\n");
    sb.append("    blockTimestamp: ").append(toIndentedString(blockTimestamp)).append("\n");
    sb.append("    blockHash: ").append(toIndentedString(blockHash)).append("\n");
    sb.append("    txCount: ").append(toIndentedString(txCount)).append("\n");
    sb.append("    atomicTxCount: ").append(toIndentedString(atomicTxCount)).append("\n");
    sb.append("    baseFee: ").append(toIndentedString(baseFee)).append("\n");
    sb.append("    gasUsed: ").append(toIndentedString(gasUsed)).append("\n");
    sb.append("    gasLimit: ").append(toIndentedString(gasLimit)).append("\n");
    sb.append("    gasCost: ").append(toIndentedString(gasCost)).append("\n");
    sb.append("    parentHash: ").append(toIndentedString(parentHash)).append("\n");
    sb.append("    feesSpent: ").append(toIndentedString(feesSpent)).append("\n");
    sb.append("    cumulativeTransactions: ").append(toIndentedString(cumulativeTransactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
