/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ChainStatus;
import io.swagger.client.model.NetworkToken;
import io.swagger.client.model.UtilityAddresses;
import io.swagger.client.model.VmName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * GetChainResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class GetChainResponse {
  @SerializedName("chainId")
  private String chainId = null;

  @SerializedName("status")
  private ChainStatus status = null;

  @SerializedName("chainName")
  private String chainName = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("platformChainId")
  private String platformChainId = null;

  @SerializedName("subnetId")
  private String subnetId = null;

  @SerializedName("vmId")
  private String vmId = null;

  @SerializedName("vmName")
  private VmName vmName = null;

  @SerializedName("explorerUrl")
  private String explorerUrl = null;

  @SerializedName("rpcUrl")
  private String rpcUrl = null;

  @SerializedName("wsUrl")
  private String wsUrl = null;

  @SerializedName("isTestnet")
  private Boolean isTestnet = null;

  @SerializedName("utilityAddresses")
  private UtilityAddresses utilityAddresses = null;

  @SerializedName("networkToken")
  private NetworkToken networkToken = null;

  @SerializedName("chainLogoUri")
  private String chainLogoUri = null;

  public GetChainResponse chainId(String chainId) {
    this.chainId = chainId;
    return this;
  }

   /**
   * Get chainId
   * @return chainId
  **/
  @Schema(required = true, description = "")
  public String getChainId() {
    return chainId;
  }

  public void setChainId(String chainId) {
    this.chainId = chainId;
  }

  public GetChainResponse status(ChainStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public ChainStatus getStatus() {
    return status;
  }

  public void setStatus(ChainStatus status) {
    this.status = status;
  }

  public GetChainResponse chainName(String chainName) {
    this.chainName = chainName;
    return this;
  }

   /**
   * Get chainName
   * @return chainName
  **/
  @Schema(required = true, description = "")
  public String getChainName() {
    return chainName;
  }

  public void setChainName(String chainName) {
    this.chainName = chainName;
  }

  public GetChainResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public GetChainResponse platformChainId(String platformChainId) {
    this.platformChainId = platformChainId;
    return this;
  }

   /**
   * Get platformChainId
   * @return platformChainId
  **/
  @Schema(description = "")
  public String getPlatformChainId() {
    return platformChainId;
  }

  public void setPlatformChainId(String platformChainId) {
    this.platformChainId = platformChainId;
  }

  public GetChainResponse subnetId(String subnetId) {
    this.subnetId = subnetId;
    return this;
  }

   /**
   * Get subnetId
   * @return subnetId
  **/
  @Schema(description = "")
  public String getSubnetId() {
    return subnetId;
  }

  public void setSubnetId(String subnetId) {
    this.subnetId = subnetId;
  }

  public GetChainResponse vmId(String vmId) {
    this.vmId = vmId;
    return this;
  }

   /**
   * Get vmId
   * @return vmId
  **/
  @Schema(description = "")
  public String getVmId() {
    return vmId;
  }

  public void setVmId(String vmId) {
    this.vmId = vmId;
  }

  public GetChainResponse vmName(VmName vmName) {
    this.vmName = vmName;
    return this;
  }

   /**
   * Get vmName
   * @return vmName
  **/
  @Schema(required = true, description = "")
  public VmName getVmName() {
    return vmName;
  }

  public void setVmName(VmName vmName) {
    this.vmName = vmName;
  }

  public GetChainResponse explorerUrl(String explorerUrl) {
    this.explorerUrl = explorerUrl;
    return this;
  }

   /**
   * Get explorerUrl
   * @return explorerUrl
  **/
  @Schema(description = "")
  public String getExplorerUrl() {
    return explorerUrl;
  }

  public void setExplorerUrl(String explorerUrl) {
    this.explorerUrl = explorerUrl;
  }

  public GetChainResponse rpcUrl(String rpcUrl) {
    this.rpcUrl = rpcUrl;
    return this;
  }

   /**
   * Get rpcUrl
   * @return rpcUrl
  **/
  @Schema(required = true, description = "")
  public String getRpcUrl() {
    return rpcUrl;
  }

  public void setRpcUrl(String rpcUrl) {
    this.rpcUrl = rpcUrl;
  }

  public GetChainResponse wsUrl(String wsUrl) {
    this.wsUrl = wsUrl;
    return this;
  }

   /**
   * Get wsUrl
   * @return wsUrl
  **/
  @Schema(description = "")
  public String getWsUrl() {
    return wsUrl;
  }

  public void setWsUrl(String wsUrl) {
    this.wsUrl = wsUrl;
  }

  public GetChainResponse isTestnet(Boolean isTestnet) {
    this.isTestnet = isTestnet;
    return this;
  }

   /**
   * Get isTestnet
   * @return isTestnet
  **/
  @Schema(required = true, description = "")
  public Boolean isIsTestnet() {
    return isTestnet;
  }

  public void setIsTestnet(Boolean isTestnet) {
    this.isTestnet = isTestnet;
  }

  public GetChainResponse utilityAddresses(UtilityAddresses utilityAddresses) {
    this.utilityAddresses = utilityAddresses;
    return this;
  }

   /**
   * Get utilityAddresses
   * @return utilityAddresses
  **/
  @Schema(description = "")
  public UtilityAddresses getUtilityAddresses() {
    return utilityAddresses;
  }

  public void setUtilityAddresses(UtilityAddresses utilityAddresses) {
    this.utilityAddresses = utilityAddresses;
  }

  public GetChainResponse networkToken(NetworkToken networkToken) {
    this.networkToken = networkToken;
    return this;
  }

   /**
   * Get networkToken
   * @return networkToken
  **/
  @Schema(required = true, description = "")
  public NetworkToken getNetworkToken() {
    return networkToken;
  }

  public void setNetworkToken(NetworkToken networkToken) {
    this.networkToken = networkToken;
  }

  public GetChainResponse chainLogoUri(String chainLogoUri) {
    this.chainLogoUri = chainLogoUri;
    return this;
  }

   /**
   * Get chainLogoUri
   * @return chainLogoUri
  **/
  @Schema(description = "")
  public String getChainLogoUri() {
    return chainLogoUri;
  }

  public void setChainLogoUri(String chainLogoUri) {
    this.chainLogoUri = chainLogoUri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetChainResponse getChainResponse = (GetChainResponse) o;
    return Objects.equals(this.chainId, getChainResponse.chainId) &&
        Objects.equals(this.status, getChainResponse.status) &&
        Objects.equals(this.chainName, getChainResponse.chainName) &&
        Objects.equals(this.description, getChainResponse.description) &&
        Objects.equals(this.platformChainId, getChainResponse.platformChainId) &&
        Objects.equals(this.subnetId, getChainResponse.subnetId) &&
        Objects.equals(this.vmId, getChainResponse.vmId) &&
        Objects.equals(this.vmName, getChainResponse.vmName) &&
        Objects.equals(this.explorerUrl, getChainResponse.explorerUrl) &&
        Objects.equals(this.rpcUrl, getChainResponse.rpcUrl) &&
        Objects.equals(this.wsUrl, getChainResponse.wsUrl) &&
        Objects.equals(this.isTestnet, getChainResponse.isTestnet) &&
        Objects.equals(this.utilityAddresses, getChainResponse.utilityAddresses) &&
        Objects.equals(this.networkToken, getChainResponse.networkToken) &&
        Objects.equals(this.chainLogoUri, getChainResponse.chainLogoUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chainId, status, chainName, description, platformChainId, subnetId, vmId, vmName, explorerUrl, rpcUrl, wsUrl, isTestnet, utilityAddresses, networkToken, chainLogoUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetChainResponse {\n");
    
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    chainName: ").append(toIndentedString(chainName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    platformChainId: ").append(toIndentedString(platformChainId)).append("\n");
    sb.append("    subnetId: ").append(toIndentedString(subnetId)).append("\n");
    sb.append("    vmId: ").append(toIndentedString(vmId)).append("\n");
    sb.append("    vmName: ").append(toIndentedString(vmName)).append("\n");
    sb.append("    explorerUrl: ").append(toIndentedString(explorerUrl)).append("\n");
    sb.append("    rpcUrl: ").append(toIndentedString(rpcUrl)).append("\n");
    sb.append("    wsUrl: ").append(toIndentedString(wsUrl)).append("\n");
    sb.append("    isTestnet: ").append(toIndentedString(isTestnet)).append("\n");
    sb.append("    utilityAddresses: ").append(toIndentedString(utilityAddresses)).append("\n");
    sb.append("    networkToken: ").append(toIndentedString(networkToken)).append("\n");
    sb.append("    chainLogoUri: ").append(toIndentedString(chainLogoUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
