/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Erc20TokenBalance;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ListErc20BalancesResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class ListErc20BalancesResponse {
  @SerializedName("nextPageToken")
  private String nextPageToken = null;

  @SerializedName("erc20TokenBalances")
  private List<Erc20TokenBalance> erc20TokenBalances = new ArrayList<Erc20TokenBalance>();

  public ListErc20BalancesResponse nextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

   /**
   * A token, which can be sent as &#x60;pageToken&#x60; to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.
   * @return nextPageToken
  **/
  @Schema(description = "A token, which can be sent as `pageToken` to retrieve the next page. If this field is omitted or empty, there are no subsequent pages.")
  public String getNextPageToken() {
    return nextPageToken;
  }

  public void setNextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }

  public ListErc20BalancesResponse erc20TokenBalances(List<Erc20TokenBalance> erc20TokenBalances) {
    this.erc20TokenBalances = erc20TokenBalances;
    return this;
  }

  public ListErc20BalancesResponse addErc20TokenBalancesItem(Erc20TokenBalance erc20TokenBalancesItem) {
    this.erc20TokenBalances.add(erc20TokenBalancesItem);
    return this;
  }

   /**
   * The list of ERC-20 token balances for the address.
   * @return erc20TokenBalances
  **/
  @Schema(required = true, description = "The list of ERC-20 token balances for the address.")
  public List<Erc20TokenBalance> getErc20TokenBalances() {
    return erc20TokenBalances;
  }

  public void setErc20TokenBalances(List<Erc20TokenBalance> erc20TokenBalances) {
    this.erc20TokenBalances = erc20TokenBalances;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListErc20BalancesResponse listErc20BalancesResponse = (ListErc20BalancesResponse) o;
    return Objects.equals(this.nextPageToken, listErc20BalancesResponse.nextPageToken) &&
        Objects.equals(this.erc20TokenBalances, listErc20BalancesResponse.erc20TokenBalances);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nextPageToken, erc20TokenBalances);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListErc20BalancesResponse {\n");
    
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("    erc20TokenBalances: ").append(toIndentedString(erc20TokenBalances)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
