/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.TransactionMethodType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Method
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class Method {
  @SerializedName("callType")
  private TransactionMethodType callType = null;

  @SerializedName("methodHash")
  private String methodHash = null;

  @SerializedName("methodName")
  private String methodName = null;

  public Method callType(TransactionMethodType callType) {
    this.callType = callType;
    return this;
  }

   /**
   * Get callType
   * @return callType
  **/
  @Schema(required = true, description = "")
  public TransactionMethodType getCallType() {
    return callType;
  }

  public void setCallType(TransactionMethodType callType) {
    this.callType = callType;
  }

  public Method methodHash(String methodHash) {
    this.methodHash = methodHash;
    return this;
  }

   /**
   * The contract method hash identifier. The method hash is only set if the &#x60;callType&#x60; is &#x60;CONTRACT_CALL&#x60;.
   * @return methodHash
  **/
  @Schema(example = "0xa9059cbb", required = true, description = "The contract method hash identifier. The method hash is only set if the `callType` is `CONTRACT_CALL`.")
  public String getMethodHash() {
    return methodHash;
  }

  public void setMethodHash(String methodHash) {
    this.methodHash = methodHash;
  }

  public Method methodName(String methodName) {
    this.methodName = methodName;
    return this;
  }

   /**
   * The contract method name including parameter types. If the &#x60;callType&#x60; is &#x60;NATIVE_TRANSFER&#x60; this is set to &#x27;Native Transfer&#x27;. If the &#x60;callType&#x60; is &#x60;CONTRACT_CREATION&#x60; this is set to &#x27;Contract Created&#x27;.
   * @return methodName
  **/
  @Schema(example = "transfer(address,uint256)", description = "The contract method name including parameter types. If the `callType` is `NATIVE_TRANSFER` this is set to 'Native Transfer'. If the `callType` is `CONTRACT_CREATION` this is set to 'Contract Created'.")
  public String getMethodName() {
    return methodName;
  }

  public void setMethodName(String methodName) {
    this.methodName = methodName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Method method = (Method) o;
    return Objects.equals(this.callType, method.callType) &&
        Objects.equals(this.methodHash, method.methodHash) &&
        Objects.equals(this.methodName, method.methodName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callType, methodHash, methodName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Method {\n");
    
    sb.append("    callType: ").append(toIndentedString(callType)).append("\n");
    sb.append("    methodHash: ").append(toIndentedString(methodHash)).append("\n");
    sb.append("    methodName: ").append(toIndentedString(methodName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
