/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.NetworkToken;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * NetworkTokenDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class NetworkTokenDetails {
  @SerializedName("networkToken")
  private NetworkToken networkToken = null;

  @SerializedName("currentPrice")
  private AllOfNetworkTokenDetailsCurrentPrice currentPrice = null;

  @SerializedName("historicalPrice")
  private AllOfNetworkTokenDetailsHistoricalPrice historicalPrice = null;

  public NetworkTokenDetails networkToken(NetworkToken networkToken) {
    this.networkToken = networkToken;
    return this;
  }

   /**
   * Get networkToken
   * @return networkToken
  **/
  @Schema(required = true, description = "")
  public NetworkToken getNetworkToken() {
    return networkToken;
  }

  public void setNetworkToken(NetworkToken networkToken) {
    this.networkToken = networkToken;
  }

  public NetworkTokenDetails currentPrice(AllOfNetworkTokenDetailsCurrentPrice currentPrice) {
    this.currentPrice = currentPrice;
    return this;
  }

   /**
   * The current token price, if available.
   * @return currentPrice
  **/
  @Schema(description = "The current token price, if available.")
  public AllOfNetworkTokenDetailsCurrentPrice getCurrentPrice() {
    return currentPrice;
  }

  public void setCurrentPrice(AllOfNetworkTokenDetailsCurrentPrice currentPrice) {
    this.currentPrice = currentPrice;
  }

  public NetworkTokenDetails historicalPrice(AllOfNetworkTokenDetailsHistoricalPrice historicalPrice) {
    this.historicalPrice = historicalPrice;
    return this;
  }

   /**
   * The historical token price at the time the transaction       occured, if available. Note, this is only provided if the transaction       occured more than 24 hours ago.
   * @return historicalPrice
  **/
  @Schema(description = "The historical token price at the time the transaction       occured, if available. Note, this is only provided if the transaction       occured more than 24 hours ago.")
  public AllOfNetworkTokenDetailsHistoricalPrice getHistoricalPrice() {
    return historicalPrice;
  }

  public void setHistoricalPrice(AllOfNetworkTokenDetailsHistoricalPrice historicalPrice) {
    this.historicalPrice = historicalPrice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkTokenDetails networkTokenDetails = (NetworkTokenDetails) o;
    return Objects.equals(this.networkToken, networkTokenDetails.networkToken) &&
        Objects.equals(this.currentPrice, networkTokenDetails.currentPrice) &&
        Objects.equals(this.historicalPrice, networkTokenDetails.historicalPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(networkToken, currentPrice, historicalPrice);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkTokenDetails {\n");
    
    sb.append("    networkToken: ").append(toIndentedString(networkToken)).append("\n");
    sb.append("    currentPrice: ").append(toIndentedString(currentPrice)).append("\n");
    sb.append("    historicalPrice: ").append(toIndentedString(historicalPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
