/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.OperationStatus;
import io.swagger.client.model.OperationType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * OperationStatusResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class OperationStatusResponse {
  @SerializedName("operationId")
  private String operationId = null;

  @SerializedName("operationType")
  private OperationType operationType = null;

  @SerializedName("operationStatus")
  private OperationStatus operationStatus = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("metadata")
  private OneOfOperationStatusResponseMetadata metadata = null;

  @SerializedName("createdAtTimestamp")
  private BigDecimal createdAtTimestamp = null;

  @SerializedName("updatedAtTimestamp")
  private BigDecimal updatedAtTimestamp = null;

  public OperationStatusResponse operationId(String operationId) {
    this.operationId = operationId;
    return this;
  }

   /**
   * Get operationId
   * @return operationId
  **/
  @Schema(required = true, description = "")
  public String getOperationId() {
    return operationId;
  }

  public void setOperationId(String operationId) {
    this.operationId = operationId;
  }

  public OperationStatusResponse operationType(OperationType operationType) {
    this.operationType = operationType;
    return this;
  }

   /**
   * Get operationType
   * @return operationType
  **/
  @Schema(required = true, description = "")
  public OperationType getOperationType() {
    return operationType;
  }

  public void setOperationType(OperationType operationType) {
    this.operationType = operationType;
  }

  public OperationStatusResponse operationStatus(OperationStatus operationStatus) {
    this.operationStatus = operationStatus;
    return this;
  }

   /**
   * Get operationStatus
   * @return operationStatus
  **/
  @Schema(required = true, description = "")
  public OperationStatus getOperationStatus() {
    return operationStatus;
  }

  public void setOperationStatus(OperationStatus operationStatus) {
    this.operationStatus = operationStatus;
  }

  public OperationStatusResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @Schema(description = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public OperationStatusResponse metadata(OneOfOperationStatusResponseMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @Schema(required = true, description = "")
  public OneOfOperationStatusResponseMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(OneOfOperationStatusResponseMetadata metadata) {
    this.metadata = metadata;
  }

  public OperationStatusResponse createdAtTimestamp(BigDecimal createdAtTimestamp) {
    this.createdAtTimestamp = createdAtTimestamp;
    return this;
  }

   /**
   * Get createdAtTimestamp
   * @return createdAtTimestamp
  **/
  @Schema(required = true, description = "")
  public BigDecimal getCreatedAtTimestamp() {
    return createdAtTimestamp;
  }

  public void setCreatedAtTimestamp(BigDecimal createdAtTimestamp) {
    this.createdAtTimestamp = createdAtTimestamp;
  }

  public OperationStatusResponse updatedAtTimestamp(BigDecimal updatedAtTimestamp) {
    this.updatedAtTimestamp = updatedAtTimestamp;
    return this;
  }

   /**
   * Get updatedAtTimestamp
   * @return updatedAtTimestamp
  **/
  @Schema(required = true, description = "")
  public BigDecimal getUpdatedAtTimestamp() {
    return updatedAtTimestamp;
  }

  public void setUpdatedAtTimestamp(BigDecimal updatedAtTimestamp) {
    this.updatedAtTimestamp = updatedAtTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationStatusResponse operationStatusResponse = (OperationStatusResponse) o;
    return Objects.equals(this.operationId, operationStatusResponse.operationId) &&
        Objects.equals(this.operationType, operationStatusResponse.operationType) &&
        Objects.equals(this.operationStatus, operationStatusResponse.operationStatus) &&
        Objects.equals(this.message, operationStatusResponse.message) &&
        Objects.equals(this.metadata, operationStatusResponse.metadata) &&
        Objects.equals(this.createdAtTimestamp, operationStatusResponse.createdAtTimestamp) &&
        Objects.equals(this.updatedAtTimestamp, operationStatusResponse.updatedAtTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operationId, operationType, operationStatus, message, metadata, createdAtTimestamp, updatedAtTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationStatusResponse {\n");
    
    sb.append("    operationId: ").append(toIndentedString(operationId)).append("\n");
    sb.append("    operationType: ").append(toIndentedString(operationType)).append("\n");
    sb.append("    operationStatus: ").append(toIndentedString(operationStatus)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    createdAtTimestamp: ").append(toIndentedString(createdAtTimestamp)).append("\n");
    sb.append("    updatedAtTimestamp: ").append(toIndentedString(updatedAtTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
