/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * PChainUtxo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class PChainUtxo {
  @SerializedName("addresses")
  private List<String> addresses = new ArrayList<String>();

  @SerializedName("utxoId")
  private String utxoId = null;

  @SerializedName("txHash")
  private String txHash = null;

  @SerializedName("outputIndex")
  private BigDecimal outputIndex = null;

  @SerializedName("blockTimestamp")
  private BigDecimal blockTimestamp = null;

  @SerializedName("consumingTxHash")
  private String consumingTxHash = null;

  @SerializedName("consumingBlockTimestamp")
  private BigDecimal consumingBlockTimestamp = null;

  @SerializedName("assetId")
  private String assetId = null;

  @SerializedName("utxoType")
  private String utxoType = null;

  @SerializedName("amount")
  private String amount = null;

  @SerializedName("stakeableLocktime")
  private BigDecimal stakeableLocktime = null;

  @SerializedName("platformLocktime")
  private BigDecimal platformLocktime = null;

  @SerializedName("threshold")
  private BigDecimal threshold = null;

  @SerializedName("createdOnChainId")
  private String createdOnChainId = null;

  @SerializedName("consumedOnChainId")
  private String consumedOnChainId = null;

  public PChainUtxo addresses(List<String> addresses) {
    this.addresses = addresses;
    return this;
  }

  public PChainUtxo addAddressesItem(String addressesItem) {
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * An array of P-Chain wallet addresses.
   * @return addresses
  **/
  @Schema(example = "[\"avax1h2ccj9f5ay5acl6tyn9mwmw32p8wref8vl8ctg\"]", required = true, description = "An array of P-Chain wallet addresses.")
  public List<String> getAddresses() {
    return addresses;
  }

  public void setAddresses(List<String> addresses) {
    this.addresses = addresses;
  }

  public PChainUtxo utxoId(String utxoId) {
    this.utxoId = utxoId;
    return this;
  }

   /**
   * Get utxoId
   * @return utxoId
  **/
  @Schema(required = true, description = "")
  public String getUtxoId() {
    return utxoId;
  }

  public void setUtxoId(String utxoId) {
    this.utxoId = utxoId;
  }

  public PChainUtxo txHash(String txHash) {
    this.txHash = txHash;
    return this;
  }

   /**
   * Get txHash
   * @return txHash
  **/
  @Schema(required = true, description = "")
  public String getTxHash() {
    return txHash;
  }

  public void setTxHash(String txHash) {
    this.txHash = txHash;
  }

  public PChainUtxo outputIndex(BigDecimal outputIndex) {
    this.outputIndex = outputIndex;
    return this;
  }

   /**
   * Get outputIndex
   * @return outputIndex
  **/
  @Schema(required = true, description = "")
  public BigDecimal getOutputIndex() {
    return outputIndex;
  }

  public void setOutputIndex(BigDecimal outputIndex) {
    this.outputIndex = outputIndex;
  }

  public PChainUtxo blockTimestamp(BigDecimal blockTimestamp) {
    this.blockTimestamp = blockTimestamp;
    return this;
  }

   /**
   * Get blockTimestamp
   * @return blockTimestamp
  **/
  @Schema(required = true, description = "")
  public BigDecimal getBlockTimestamp() {
    return blockTimestamp;
  }

  public void setBlockTimestamp(BigDecimal blockTimestamp) {
    this.blockTimestamp = blockTimestamp;
  }

  public PChainUtxo consumingTxHash(String consumingTxHash) {
    this.consumingTxHash = consumingTxHash;
    return this;
  }

   /**
   * Get consumingTxHash
   * @return consumingTxHash
  **/
  @Schema(description = "")
  public String getConsumingTxHash() {
    return consumingTxHash;
  }

  public void setConsumingTxHash(String consumingTxHash) {
    this.consumingTxHash = consumingTxHash;
  }

  public PChainUtxo consumingBlockTimestamp(BigDecimal consumingBlockTimestamp) {
    this.consumingBlockTimestamp = consumingBlockTimestamp;
    return this;
  }

   /**
   * Get consumingBlockTimestamp
   * @return consumingBlockTimestamp
  **/
  @Schema(description = "")
  public BigDecimal getConsumingBlockTimestamp() {
    return consumingBlockTimestamp;
  }

  public void setConsumingBlockTimestamp(BigDecimal consumingBlockTimestamp) {
    this.consumingBlockTimestamp = consumingBlockTimestamp;
  }

  public PChainUtxo assetId(String assetId) {
    this.assetId = assetId;
    return this;
  }

   /**
   * Get assetId
   * @return assetId
  **/
  @Schema(required = true, description = "")
  public String getAssetId() {
    return assetId;
  }

  public void setAssetId(String assetId) {
    this.assetId = assetId;
  }

  public PChainUtxo utxoType(String utxoType) {
    this.utxoType = utxoType;
    return this;
  }

   /**
   * Get utxoType
   * @return utxoType
  **/
  @Schema(required = true, description = "")
  public String getUtxoType() {
    return utxoType;
  }

  public void setUtxoType(String utxoType) {
    this.utxoType = utxoType;
  }

  public PChainUtxo amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @Schema(required = true, description = "")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public PChainUtxo stakeableLocktime(BigDecimal stakeableLocktime) {
    this.stakeableLocktime = stakeableLocktime;
    return this;
  }

   /**
   * Get stakeableLocktime
   * @return stakeableLocktime
  **/
  @Schema(description = "")
  public BigDecimal getStakeableLocktime() {
    return stakeableLocktime;
  }

  public void setStakeableLocktime(BigDecimal stakeableLocktime) {
    this.stakeableLocktime = stakeableLocktime;
  }

  public PChainUtxo platformLocktime(BigDecimal platformLocktime) {
    this.platformLocktime = platformLocktime;
    return this;
  }

   /**
   * Get platformLocktime
   * @return platformLocktime
  **/
  @Schema(description = "")
  public BigDecimal getPlatformLocktime() {
    return platformLocktime;
  }

  public void setPlatformLocktime(BigDecimal platformLocktime) {
    this.platformLocktime = platformLocktime;
  }

  public PChainUtxo threshold(BigDecimal threshold) {
    this.threshold = threshold;
    return this;
  }

   /**
   * Get threshold
   * @return threshold
  **/
  @Schema(description = "")
  public BigDecimal getThreshold() {
    return threshold;
  }

  public void setThreshold(BigDecimal threshold) {
    this.threshold = threshold;
  }

  public PChainUtxo createdOnChainId(String createdOnChainId) {
    this.createdOnChainId = createdOnChainId;
    return this;
  }

   /**
   * Get createdOnChainId
   * @return createdOnChainId
  **/
  @Schema(required = true, description = "")
  public String getCreatedOnChainId() {
    return createdOnChainId;
  }

  public void setCreatedOnChainId(String createdOnChainId) {
    this.createdOnChainId = createdOnChainId;
  }

  public PChainUtxo consumedOnChainId(String consumedOnChainId) {
    this.consumedOnChainId = consumedOnChainId;
    return this;
  }

   /**
   * Get consumedOnChainId
   * @return consumedOnChainId
  **/
  @Schema(required = true, description = "")
  public String getConsumedOnChainId() {
    return consumedOnChainId;
  }

  public void setConsumedOnChainId(String consumedOnChainId) {
    this.consumedOnChainId = consumedOnChainId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PChainUtxo pchainUtxo = (PChainUtxo) o;
    return Objects.equals(this.addresses, pchainUtxo.addresses) &&
        Objects.equals(this.utxoId, pchainUtxo.utxoId) &&
        Objects.equals(this.txHash, pchainUtxo.txHash) &&
        Objects.equals(this.outputIndex, pchainUtxo.outputIndex) &&
        Objects.equals(this.blockTimestamp, pchainUtxo.blockTimestamp) &&
        Objects.equals(this.consumingTxHash, pchainUtxo.consumingTxHash) &&
        Objects.equals(this.consumingBlockTimestamp, pchainUtxo.consumingBlockTimestamp) &&
        Objects.equals(this.assetId, pchainUtxo.assetId) &&
        Objects.equals(this.utxoType, pchainUtxo.utxoType) &&
        Objects.equals(this.amount, pchainUtxo.amount) &&
        Objects.equals(this.stakeableLocktime, pchainUtxo.stakeableLocktime) &&
        Objects.equals(this.platformLocktime, pchainUtxo.platformLocktime) &&
        Objects.equals(this.threshold, pchainUtxo.threshold) &&
        Objects.equals(this.createdOnChainId, pchainUtxo.createdOnChainId) &&
        Objects.equals(this.consumedOnChainId, pchainUtxo.consumedOnChainId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addresses, utxoId, txHash, outputIndex, blockTimestamp, consumingTxHash, consumingBlockTimestamp, assetId, utxoType, amount, stakeableLocktime, platformLocktime, threshold, createdOnChainId, consumedOnChainId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PChainUtxo {\n");
    
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    utxoId: ").append(toIndentedString(utxoId)).append("\n");
    sb.append("    txHash: ").append(toIndentedString(txHash)).append("\n");
    sb.append("    outputIndex: ").append(toIndentedString(outputIndex)).append("\n");
    sb.append("    blockTimestamp: ").append(toIndentedString(blockTimestamp)).append("\n");
    sb.append("    consumingTxHash: ").append(toIndentedString(consumingTxHash)).append("\n");
    sb.append("    consumingBlockTimestamp: ").append(toIndentedString(consumingBlockTimestamp)).append("\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    utxoType: ").append(toIndentedString(utxoType)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    stakeableLocktime: ").append(toIndentedString(stakeableLocktime)).append("\n");
    sb.append("    platformLocktime: ").append(toIndentedString(platformLocktime)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    createdOnChainId: ").append(toIndentedString(createdOnChainId)).append("\n");
    sb.append("    consumedOnChainId: ").append(toIndentedString(consumedOnChainId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
