/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PChainAsset;
import io.swagger.client.model.PChainConsumedUtxo;
import io.swagger.client.model.PChainEmittedUtxo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * PChainTransaction
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class PChainTransaction implements InlineResponse2001 {
  @SerializedName("txHash")
  private String txHash = null;

  @SerializedName("txType")
  private String txType = null;

  @SerializedName("blockTimestamp")
  private BigDecimal blockTimestamp = null;

  @SerializedName("blockNumber")
  private String blockNumber = null;

  @SerializedName("blockHash")
  private String blockHash = null;

  @SerializedName("consumedUtxos")
  private List<PChainConsumedUtxo> consumedUtxos = null;

  @SerializedName("emittedUtxos")
  private List<PChainEmittedUtxo> emittedUtxos = null;

  @SerializedName("sourceChain")
  private String sourceChain = null;

  @SerializedName("destinationChain")
  private String destinationChain = null;

  @SerializedName("value")
  private List<PChainAsset> value = null;

  @SerializedName("amountBurned")
  private List<PChainAsset> amountBurned = null;

  @SerializedName("amountStaked")
  private List<PChainAsset> amountStaked = null;

  @SerializedName("startTimestamp")
  private BigDecimal startTimestamp = null;

  @SerializedName("endTimestamp")
  private BigDecimal endTimestamp = null;

  @SerializedName("delegationFeePercent")
  private String delegationFeePercent = null;

  @SerializedName("nodeId")
  private String nodeId = null;

  @SerializedName("subnetId")
  private String subnetId = null;

  @SerializedName("estimatedReward")
  private String estimatedReward = null;

  @SerializedName("rewardTx")
  private String rewardTx = null;

  @SerializedName("memo")
  private String memo = null;

  @SerializedName("stakingTxHash")
  private String stakingTxHash = null;

  public PChainTransaction txHash(String txHash) {
    this.txHash = txHash;
    return this;
  }

   /**
   * A P-Chain transaction hash.
   * @return txHash
  **/
  @Schema(example = "3P91K6nuDFvDodcRuJTsgdf9SvYe5pMiKk38HppsoeAiEztCP", required = true, description = "A P-Chain transaction hash.")
  public String getTxHash() {
    return txHash;
  }

  public void setTxHash(String txHash) {
    this.txHash = txHash;
  }

  public PChainTransaction txType(String txType) {
    this.txType = txType;
    return this;
  }

   /**
   * Get txType
   * @return txType
  **/
  @Schema(required = true, description = "")
  public String getTxType() {
    return txType;
  }

  public void setTxType(String txType) {
    this.txType = txType;
  }

  public PChainTransaction blockTimestamp(BigDecimal blockTimestamp) {
    this.blockTimestamp = blockTimestamp;
    return this;
  }

   /**
   * The block finality timestamp.
   * @return blockTimestamp
  **/
  @Schema(example = "1648672486", required = true, description = "The block finality timestamp.")
  public BigDecimal getBlockTimestamp() {
    return blockTimestamp;
  }

  public void setBlockTimestamp(BigDecimal blockTimestamp) {
    this.blockTimestamp = blockTimestamp;
  }

  public PChainTransaction blockNumber(String blockNumber) {
    this.blockNumber = blockNumber;
    return this;
  }

   /**
   * Get blockNumber
   * @return blockNumber
  **/
  @Schema(required = true, description = "")
  public String getBlockNumber() {
    return blockNumber;
  }

  public void setBlockNumber(String blockNumber) {
    this.blockNumber = blockNumber;
  }

  public PChainTransaction blockHash(String blockHash) {
    this.blockHash = blockHash;
    return this;
  }

   /**
   * Get blockHash
   * @return blockHash
  **/
  @Schema(required = true, description = "")
  public String getBlockHash() {
    return blockHash;
  }

  public void setBlockHash(String blockHash) {
    this.blockHash = blockHash;
  }

  public PChainTransaction consumedUtxos(List<PChainConsumedUtxo> consumedUtxos) {
    this.consumedUtxos = consumedUtxos;
    return this;
  }

  public PChainTransaction addConsumedUtxosItem(PChainConsumedUtxo consumedUtxosItem) {
    if (this.consumedUtxos == null) {
      this.consumedUtxos = new ArrayList<PChainConsumedUtxo>();
    }
    this.consumedUtxos.add(consumedUtxosItem);
    return this;
  }

   /**
   * A list of objects containing consumed UTXO info pertaining to a given transaction.
   * @return consumedUtxos
  **/
  @Schema(example = "[{\"fromTx\":\"2PcqHRFugJdjDApByTFFUaNpKkjPnUa4QKX4pzgZWJwcVwQWaC\",\"addresses\":[\"avax19wf84mm09uxld37v6sgky6l7028pr092l0g6tv\"],\"amount\":\"22500000000000\",\"assetId\":\"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z\",\"utxoId\":\"17zW4hNQ3SWW7jvq2mv4ausNZN8Zt6MiaTALDcDkydrDsyPod\"}]", description = "A list of objects containing consumed UTXO info pertaining to a given transaction.")
  public List<PChainConsumedUtxo> getConsumedUtxos() {
    return consumedUtxos;
  }

  public void setConsumedUtxos(List<PChainConsumedUtxo> consumedUtxos) {
    this.consumedUtxos = consumedUtxos;
  }

  public PChainTransaction emittedUtxos(List<PChainEmittedUtxo> emittedUtxos) {
    this.emittedUtxos = emittedUtxos;
    return this;
  }

  public PChainTransaction addEmittedUtxosItem(PChainEmittedUtxo emittedUtxosItem) {
    if (this.emittedUtxos == null) {
      this.emittedUtxos = new ArrayList<PChainEmittedUtxo>();
    }
    this.emittedUtxos.add(emittedUtxosItem);
    return this;
  }

   /**
   * A list of objects containing emitted UTXO info pertaining to a given transaction.
   * @return emittedUtxos
  **/
  @Schema(example = "[{\"toTx\":\"2PcqHRFugJdjDApByTFFUaNpKkjPnUa4QKX4pzgZWJwcVwQWaC\",\"addresses\":[\"avax19wf84mm09uxld37v6sgky6l7028pr092l0g6tv\"],\"amount\":\"22500000000000\",\"assetId\":\"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z\",\"utxoId\":\"17zW4hNQ3SWW7jvq2mv4ausNZN8Zt6MiaTALDcDkydrDsyPod\"}]", description = "A list of objects containing emitted UTXO info pertaining to a given transaction.")
  public List<PChainEmittedUtxo> getEmittedUtxos() {
    return emittedUtxos;
  }

  public void setEmittedUtxos(List<PChainEmittedUtxo> emittedUtxos) {
    this.emittedUtxos = emittedUtxos;
  }

  public PChainTransaction sourceChain(String sourceChain) {
    this.sourceChain = sourceChain;
    return this;
  }

   /**
   * Source chain for an atomic transaction.
   * @return sourceChain
  **/
  @Schema(example = "2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM", description = "Source chain for an atomic transaction.")
  public String getSourceChain() {
    return sourceChain;
  }

  public void setSourceChain(String sourceChain) {
    this.sourceChain = sourceChain;
  }

  public PChainTransaction destinationChain(String destinationChain) {
    this.destinationChain = destinationChain;
    return this;
  }

   /**
   * Destination chain for an atomic transaction.
   * @return destinationChain
  **/
  @Schema(example = "2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM", description = "Destination chain for an atomic transaction.")
  public String getDestinationChain() {
    return destinationChain;
  }

  public void setDestinationChain(String destinationChain) {
    this.destinationChain = destinationChain;
  }

  public PChainTransaction value(List<PChainAsset> value) {
    this.value = value;
    return this;
  }

  public PChainTransaction addValueItem(PChainAsset valueItem) {
    if (this.value == null) {
      this.value = new ArrayList<PChainAsset>();
    }
    this.value.add(valueItem);
    return this;
  }

   /**
   * A list of objects containing P-chain Asset ID and the amount of that Asset ID.
   * @return value
  **/
  @Schema(example = "[{\"assetId\":\"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z\",\"amount\":\"100000000\"}]", description = "A list of objects containing P-chain Asset ID and the amount of that Asset ID.")
  public List<PChainAsset> getValue() {
    return value;
  }

  public void setValue(List<PChainAsset> value) {
    this.value = value;
  }

  public PChainTransaction amountBurned(List<PChainAsset> amountBurned) {
    this.amountBurned = amountBurned;
    return this;
  }

  public PChainTransaction addAmountBurnedItem(PChainAsset amountBurnedItem) {
    if (this.amountBurned == null) {
      this.amountBurned = new ArrayList<PChainAsset>();
    }
    this.amountBurned.add(amountBurnedItem);
    return this;
  }

   /**
   * A list of objects containing P-chain Asset ID and the amount of that Asset ID.
   * @return amountBurned
  **/
  @Schema(example = "[{\"assetId\":\"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z\",\"amount\":\"100000000\"}]", description = "A list of objects containing P-chain Asset ID and the amount of that Asset ID.")
  public List<PChainAsset> getAmountBurned() {
    return amountBurned;
  }

  public void setAmountBurned(List<PChainAsset> amountBurned) {
    this.amountBurned = amountBurned;
  }

  public PChainTransaction amountStaked(List<PChainAsset> amountStaked) {
    this.amountStaked = amountStaked;
    return this;
  }

  public PChainTransaction addAmountStakedItem(PChainAsset amountStakedItem) {
    if (this.amountStaked == null) {
      this.amountStaked = new ArrayList<PChainAsset>();
    }
    this.amountStaked.add(amountStakedItem);
    return this;
  }

   /**
   * A list of objects containing P-chain Asset ID and the amount of that Asset ID. Present for AddValidatorTx, AddPermissionlessValidatorTx, AddDelegatorTx
   * @return amountStaked
  **/
  @Schema(example = "[{\"assetId\":\"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z\",\"amount\":\"100000000\"}]", description = "A list of objects containing P-chain Asset ID and the amount of that Asset ID. Present for AddValidatorTx, AddPermissionlessValidatorTx, AddDelegatorTx")
  public List<PChainAsset> getAmountStaked() {
    return amountStaked;
  }

  public void setAmountStaked(List<PChainAsset> amountStaked) {
    this.amountStaked = amountStaked;
  }

  public PChainTransaction startTimestamp(BigDecimal startTimestamp) {
    this.startTimestamp = startTimestamp;
    return this;
  }

   /**
   * Present for AddValidatorTx, AddSubnetValidatorTx, AddPermissionlessValidatorTx, AddDelegatorTx
   * @return startTimestamp
  **/
  @Schema(description = "Present for AddValidatorTx, AddSubnetValidatorTx, AddPermissionlessValidatorTx, AddDelegatorTx")
  public BigDecimal getStartTimestamp() {
    return startTimestamp;
  }

  public void setStartTimestamp(BigDecimal startTimestamp) {
    this.startTimestamp = startTimestamp;
  }

  public PChainTransaction endTimestamp(BigDecimal endTimestamp) {
    this.endTimestamp = endTimestamp;
    return this;
  }

   /**
   * Present for AddValidatorTx, AddSubnetValidatorTx, AddPermissionlessValidatorTx, AddDelegatorTx
   * @return endTimestamp
  **/
  @Schema(description = "Present for AddValidatorTx, AddSubnetValidatorTx, AddPermissionlessValidatorTx, AddDelegatorTx")
  public BigDecimal getEndTimestamp() {
    return endTimestamp;
  }

  public void setEndTimestamp(BigDecimal endTimestamp) {
    this.endTimestamp = endTimestamp;
  }

  public PChainTransaction delegationFeePercent(String delegationFeePercent) {
    this.delegationFeePercent = delegationFeePercent;
    return this;
  }

   /**
   * Present for AddValidatorTx, AddPermissionlessValidatorTx
   * @return delegationFeePercent
  **/
  @Schema(description = "Present for AddValidatorTx, AddPermissionlessValidatorTx")
  public String getDelegationFeePercent() {
    return delegationFeePercent;
  }

  public void setDelegationFeePercent(String delegationFeePercent) {
    this.delegationFeePercent = delegationFeePercent;
  }

  public PChainTransaction nodeId(String nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Present for AddValidatorTx, AddSubnetValidatorTx, RemoveSubnetValidatorTx, AddPermissionlessValidatorTx, AddDelegatorTx
   * @return nodeId
  **/
  @Schema(description = "Present for AddValidatorTx, AddSubnetValidatorTx, RemoveSubnetValidatorTx, AddPermissionlessValidatorTx, AddDelegatorTx")
  public String getNodeId() {
    return nodeId;
  }

  public void setNodeId(String nodeId) {
    this.nodeId = nodeId;
  }

  public PChainTransaction subnetId(String subnetId) {
    this.subnetId = subnetId;
    return this;
  }

   /**
   * Present for AddValidatorTx, AddSubnetValidatorTx, RemoveSubnetValidatorTx, AddPermissionlessValidatorTx, AddDelegatorTx, CreateChainTx, CreateSubnetTx
   * @return subnetId
  **/
  @Schema(description = "Present for AddValidatorTx, AddSubnetValidatorTx, RemoveSubnetValidatorTx, AddPermissionlessValidatorTx, AddDelegatorTx, CreateChainTx, CreateSubnetTx")
  public String getSubnetId() {
    return subnetId;
  }

  public void setSubnetId(String subnetId) {
    this.subnetId = subnetId;
  }

  public PChainTransaction estimatedReward(String estimatedReward) {
    this.estimatedReward = estimatedReward;
    return this;
  }

   /**
   * Present for AddValidatorTx, AddPermissionlessValidatorTx, AddDelegatorTx
   * @return estimatedReward
  **/
  @Schema(description = "Present for AddValidatorTx, AddPermissionlessValidatorTx, AddDelegatorTx")
  public String getEstimatedReward() {
    return estimatedReward;
  }

  public void setEstimatedReward(String estimatedReward) {
    this.estimatedReward = estimatedReward;
  }

  public PChainTransaction rewardTx(String rewardTx) {
    this.rewardTx = rewardTx;
    return this;
  }

   /**
   * Get rewardTx
   * @return rewardTx
  **/
  @Schema(description = "")
  public String getRewardTx() {
    return rewardTx;
  }

  public void setRewardTx(String rewardTx) {
    this.rewardTx = rewardTx;
  }

  public PChainTransaction memo(String memo) {
    this.memo = memo;
    return this;
  }

   /**
   * Get memo
   * @return memo
  **/
  @Schema(description = "")
  public String getMemo() {
    return memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  public PChainTransaction stakingTxHash(String stakingTxHash) {
    this.stakingTxHash = stakingTxHash;
    return this;
  }

   /**
   * Present for RewardValidatorTx
   * @return stakingTxHash
  **/
  @Schema(description = "Present for RewardValidatorTx")
  public String getStakingTxHash() {
    return stakingTxHash;
  }

  public void setStakingTxHash(String stakingTxHash) {
    this.stakingTxHash = stakingTxHash;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PChainTransaction pchainTransaction = (PChainTransaction) o;
    return Objects.equals(this.txHash, pchainTransaction.txHash) &&
        Objects.equals(this.txType, pchainTransaction.txType) &&
        Objects.equals(this.blockTimestamp, pchainTransaction.blockTimestamp) &&
        Objects.equals(this.blockNumber, pchainTransaction.blockNumber) &&
        Objects.equals(this.blockHash, pchainTransaction.blockHash) &&
        Objects.equals(this.consumedUtxos, pchainTransaction.consumedUtxos) &&
        Objects.equals(this.emittedUtxos, pchainTransaction.emittedUtxos) &&
        Objects.equals(this.sourceChain, pchainTransaction.sourceChain) &&
        Objects.equals(this.destinationChain, pchainTransaction.destinationChain) &&
        Objects.equals(this.value, pchainTransaction.value) &&
        Objects.equals(this.amountBurned, pchainTransaction.amountBurned) &&
        Objects.equals(this.amountStaked, pchainTransaction.amountStaked) &&
        Objects.equals(this.startTimestamp, pchainTransaction.startTimestamp) &&
        Objects.equals(this.endTimestamp, pchainTransaction.endTimestamp) &&
        Objects.equals(this.delegationFeePercent, pchainTransaction.delegationFeePercent) &&
        Objects.equals(this.nodeId, pchainTransaction.nodeId) &&
        Objects.equals(this.subnetId, pchainTransaction.subnetId) &&
        Objects.equals(this.estimatedReward, pchainTransaction.estimatedReward) &&
        Objects.equals(this.rewardTx, pchainTransaction.rewardTx) &&
        Objects.equals(this.memo, pchainTransaction.memo) &&
        Objects.equals(this.stakingTxHash, pchainTransaction.stakingTxHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(txHash, txType, blockTimestamp, blockNumber, blockHash, consumedUtxos, emittedUtxos, sourceChain, destinationChain, value, amountBurned, amountStaked, startTimestamp, endTimestamp, delegationFeePercent, nodeId, subnetId, estimatedReward, rewardTx, memo, stakingTxHash);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PChainTransaction {\n");
    
    sb.append("    txHash: ").append(toIndentedString(txHash)).append("\n");
    sb.append("    txType: ").append(toIndentedString(txType)).append("\n");
    sb.append("    blockTimestamp: ").append(toIndentedString(blockTimestamp)).append("\n");
    sb.append("    blockNumber: ").append(toIndentedString(blockNumber)).append("\n");
    sb.append("    blockHash: ").append(toIndentedString(blockHash)).append("\n");
    sb.append("    consumedUtxos: ").append(toIndentedString(consumedUtxos)).append("\n");
    sb.append("    emittedUtxos: ").append(toIndentedString(emittedUtxos)).append("\n");
    sb.append("    sourceChain: ").append(toIndentedString(sourceChain)).append("\n");
    sb.append("    destinationChain: ").append(toIndentedString(destinationChain)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    amountBurned: ").append(toIndentedString(amountBurned)).append("\n");
    sb.append("    amountStaked: ").append(toIndentedString(amountStaked)).append("\n");
    sb.append("    startTimestamp: ").append(toIndentedString(startTimestamp)).append("\n");
    sb.append("    endTimestamp: ").append(toIndentedString(endTimestamp)).append("\n");
    sb.append("    delegationFeePercent: ").append(toIndentedString(delegationFeePercent)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    subnetId: ").append(toIndentedString(subnetId)).append("\n");
    sb.append("    estimatedReward: ").append(toIndentedString(estimatedReward)).append("\n");
    sb.append("    rewardTx: ").append(toIndentedString(rewardTx)).append("\n");
    sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
    sb.append("    stakingTxHash: ").append(toIndentedString(stakingTxHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
