/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * ProposerDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class ProposerDetails {
  @SerializedName("proposerId")
  private String proposerId = null;

  @SerializedName("proposerParentId")
  private String proposerParentId = null;

  @SerializedName("proposerNodeId")
  private String proposerNodeId = null;

  @SerializedName("proposerPChainHeight")
  private BigDecimal proposerPChainHeight = null;

  @SerializedName("proposerTimestamp")
  private BigDecimal proposerTimestamp = null;

  public ProposerDetails proposerId(String proposerId) {
    this.proposerId = proposerId;
    return this;
  }

   /**
   * Get proposerId
   * @return proposerId
  **/
  @Schema(description = "")
  public String getProposerId() {
    return proposerId;
  }

  public void setProposerId(String proposerId) {
    this.proposerId = proposerId;
  }

  public ProposerDetails proposerParentId(String proposerParentId) {
    this.proposerParentId = proposerParentId;
    return this;
  }

   /**
   * Get proposerParentId
   * @return proposerParentId
  **/
  @Schema(description = "")
  public String getProposerParentId() {
    return proposerParentId;
  }

  public void setProposerParentId(String proposerParentId) {
    this.proposerParentId = proposerParentId;
  }

  public ProposerDetails proposerNodeId(String proposerNodeId) {
    this.proposerNodeId = proposerNodeId;
    return this;
  }

   /**
   * Get proposerNodeId
   * @return proposerNodeId
  **/
  @Schema(description = "")
  public String getProposerNodeId() {
    return proposerNodeId;
  }

  public void setProposerNodeId(String proposerNodeId) {
    this.proposerNodeId = proposerNodeId;
  }

  public ProposerDetails proposerPChainHeight(BigDecimal proposerPChainHeight) {
    this.proposerPChainHeight = proposerPChainHeight;
    return this;
  }

   /**
   * Get proposerPChainHeight
   * @return proposerPChainHeight
  **/
  @Schema(description = "")
  public BigDecimal getProposerPChainHeight() {
    return proposerPChainHeight;
  }

  public void setProposerPChainHeight(BigDecimal proposerPChainHeight) {
    this.proposerPChainHeight = proposerPChainHeight;
  }

  public ProposerDetails proposerTimestamp(BigDecimal proposerTimestamp) {
    this.proposerTimestamp = proposerTimestamp;
    return this;
  }

   /**
   * Get proposerTimestamp
   * @return proposerTimestamp
  **/
  @Schema(description = "")
  public BigDecimal getProposerTimestamp() {
    return proposerTimestamp;
  }

  public void setProposerTimestamp(BigDecimal proposerTimestamp) {
    this.proposerTimestamp = proposerTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProposerDetails proposerDetails = (ProposerDetails) o;
    return Objects.equals(this.proposerId, proposerDetails.proposerId) &&
        Objects.equals(this.proposerParentId, proposerDetails.proposerParentId) &&
        Objects.equals(this.proposerNodeId, proposerDetails.proposerNodeId) &&
        Objects.equals(this.proposerPChainHeight, proposerDetails.proposerPChainHeight) &&
        Objects.equals(this.proposerTimestamp, proposerDetails.proposerTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(proposerId, proposerParentId, proposerNodeId, proposerPChainHeight, proposerTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProposerDetails {\n");
    
    sb.append("    proposerId: ").append(toIndentedString(proposerId)).append("\n");
    sb.append("    proposerParentId: ").append(toIndentedString(proposerParentId)).append("\n");
    sb.append("    proposerNodeId: ").append(toIndentedString(proposerNodeId)).append("\n");
    sb.append("    proposerPChainHeight: ").append(toIndentedString(proposerPChainHeight)).append("\n");
    sb.append("    proposerTimestamp: ").append(toIndentedString(proposerTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
