/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Asset;
import io.swagger.client.model.UtxoCredential;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * Utxo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class Utxo {
  @SerializedName("utxoId")
  private String utxoId = null;

  @SerializedName("asset")
  private Asset asset = null;

  @SerializedName("utxoType")
  private String utxoType = null;

  @SerializedName("createdOnChainId")
  private String createdOnChainId = null;

  @SerializedName("consumedOnChainId")
  private String consumedOnChainId = null;

  @SerializedName("creationTxHash")
  private String creationTxHash = null;

  @SerializedName("consumingTxHash")
  private String consumingTxHash = null;

  @SerializedName("consumingTxTimestamp")
  private BigDecimal consumingTxTimestamp = null;

  @SerializedName("outputIndex")
  private String outputIndex = null;

  @SerializedName("timestamp")
  private BigDecimal timestamp = null;

  @SerializedName("locktime")
  private BigDecimal locktime = null;

  @SerializedName("threshold")
  private BigDecimal threshold = null;

  @SerializedName("addresses")
  private List<String> addresses = new ArrayList<String>();

  @SerializedName("credentials")
  private List<UtxoCredential> credentials = new ArrayList<UtxoCredential>();

  public Utxo utxoId(String utxoId) {
    this.utxoId = utxoId;
    return this;
  }

   /**
   * UTXO ID for this output.
   * @return utxoId
  **/
  @Schema(example = "68vLva9kfKUsX88ZPM8jdbf8qHUZRoZSFH6NdpAVTspkfrXDC", required = true, description = "UTXO ID for this output.")
  public String getUtxoId() {
    return utxoId;
  }

  public void setUtxoId(String utxoId) {
    this.utxoId = utxoId;
  }

  public Utxo asset(Asset asset) {
    this.asset = asset;
    return this;
  }

   /**
   * Get asset
   * @return asset
  **/
  @Schema(required = true, description = "")
  public Asset getAsset() {
    return asset;
  }

  public void setAsset(Asset asset) {
    this.asset = asset;
  }

  public Utxo utxoType(String utxoType) {
    this.utxoType = utxoType;
    return this;
  }

   /**
   * Type of output.
   * @return utxoType
  **/
  @Schema(example = "mint", required = true, description = "Type of output.")
  public String getUtxoType() {
    return utxoType;
  }

  public void setUtxoType(String utxoType) {
    this.utxoType = utxoType;
  }

  public Utxo createdOnChainId(String createdOnChainId) {
    this.createdOnChainId = createdOnChainId;
    return this;
  }

   /**
   * Blockchain ID on which this output is created on.
   * @return createdOnChainId
  **/
  @Schema(example = "2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM", required = true, description = "Blockchain ID on which this output is created on.")
  public String getCreatedOnChainId() {
    return createdOnChainId;
  }

  public void setCreatedOnChainId(String createdOnChainId) {
    this.createdOnChainId = createdOnChainId;
  }

  public Utxo consumedOnChainId(String consumedOnChainId) {
    this.consumedOnChainId = consumedOnChainId;
    return this;
  }

   /**
   * Blockchain ID on which this output is consumed on.
   * @return consumedOnChainId
  **/
  @Schema(example = "2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM", required = true, description = "Blockchain ID on which this output is consumed on.")
  public String getConsumedOnChainId() {
    return consumedOnChainId;
  }

  public void setConsumedOnChainId(String consumedOnChainId) {
    this.consumedOnChainId = consumedOnChainId;
  }

  public Utxo creationTxHash(String creationTxHash) {
    this.creationTxHash = creationTxHash;
    return this;
  }

   /**
   * Transaction ID that created this output.
   * @return creationTxHash
  **/
  @Schema(example = "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z", required = true, description = "Transaction ID that created this output.")
  public String getCreationTxHash() {
    return creationTxHash;
  }

  public void setCreationTxHash(String creationTxHash) {
    this.creationTxHash = creationTxHash;
  }

  public Utxo consumingTxHash(String consumingTxHash) {
    this.consumingTxHash = consumingTxHash;
    return this;
  }

   /**
   * Transaction ID that consumed this output.
   * @return consumingTxHash
  **/
  @Schema(example = "3j9JpF1aGuQtLLbo3YkvvKkWrCZViXZjdeJQWUSEY5hcqUn2c", description = "Transaction ID that consumed this output.")
  public String getConsumingTxHash() {
    return consumingTxHash;
  }

  public void setConsumingTxHash(String consumingTxHash) {
    this.consumingTxHash = consumingTxHash;
  }

  public Utxo consumingTxTimestamp(BigDecimal consumingTxTimestamp) {
    this.consumingTxTimestamp = consumingTxTimestamp;
    return this;
  }

   /**
   * Timestamp in seconds this output is consumed.
   * @return consumingTxTimestamp
  **/
  @Schema(example = "1599696000", description = "Timestamp in seconds this output is consumed.")
  public BigDecimal getConsumingTxTimestamp() {
    return consumingTxTimestamp;
  }

  public void setConsumingTxTimestamp(BigDecimal consumingTxTimestamp) {
    this.consumingTxTimestamp = consumingTxTimestamp;
  }

  public Utxo outputIndex(String outputIndex) {
    this.outputIndex = outputIndex;
    return this;
  }

   /**
   * Postion of this output in a list of lexiographically sorted outputs of a transaction.
   * @return outputIndex
  **/
  @Schema(example = "38", required = true, description = "Postion of this output in a list of lexiographically sorted outputs of a transaction.")
  public String getOutputIndex() {
    return outputIndex;
  }

  public void setOutputIndex(String outputIndex) {
    this.outputIndex = outputIndex;
  }

  public Utxo timestamp(BigDecimal timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Timestamp in seconds this outptut is created on.
   * @return timestamp
  **/
  @Schema(example = "1599696000", required = true, description = "Timestamp in seconds this outptut is created on.")
  public BigDecimal getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(BigDecimal timestamp) {
    this.timestamp = timestamp;
  }

  public Utxo locktime(BigDecimal locktime) {
    this.locktime = locktime;
    return this;
  }

   /**
   * Locktime in seconds after which this output can be consumed.
   * @return locktime
  **/
  @Schema(example = "0", required = true, description = "Locktime in seconds after which this output can be consumed.")
  public BigDecimal getLocktime() {
    return locktime;
  }

  public void setLocktime(BigDecimal locktime) {
    this.locktime = locktime;
  }

  public Utxo threshold(BigDecimal threshold) {
    this.threshold = threshold;
    return this;
  }

   /**
   * Minimum number of signatures required to consume this output.
   * @return threshold
  **/
  @Schema(example = "1", required = true, description = "Minimum number of signatures required to consume this output.")
  public BigDecimal getThreshold() {
    return threshold;
  }

  public void setThreshold(BigDecimal threshold) {
    this.threshold = threshold;
  }

  public Utxo addresses(List<String> addresses) {
    this.addresses = addresses;
    return this;
  }

  public Utxo addAddressesItem(String addressesItem) {
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * Addresses that are eligible to sign the consumption of this output.
   * @return addresses
  **/
  @Schema(example = "[\"avax1qm2a25eytsrj235hxg6jc0mwk99tss64eqevsw\"]", required = true, description = "Addresses that are eligible to sign the consumption of this output.")
  public List<String> getAddresses() {
    return addresses;
  }

  public void setAddresses(List<String> addresses) {
    this.addresses = addresses;
  }

  public Utxo credentials(List<UtxoCredential> credentials) {
    this.credentials = credentials;
    return this;
  }

  public Utxo addCredentialsItem(UtxoCredential credentialsItem) {
    this.credentials.add(credentialsItem);
    return this;
  }

   /**
   * Credentials that signed the transaction to consume this utxo
   * @return credentials
  **/
  @Schema(required = true, description = "Credentials that signed the transaction to consume this utxo")
  public List<UtxoCredential> getCredentials() {
    return credentials;
  }

  public void setCredentials(List<UtxoCredential> credentials) {
    this.credentials = credentials;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Utxo utxo = (Utxo) o;
    return Objects.equals(this.utxoId, utxo.utxoId) &&
        Objects.equals(this.asset, utxo.asset) &&
        Objects.equals(this.utxoType, utxo.utxoType) &&
        Objects.equals(this.createdOnChainId, utxo.createdOnChainId) &&
        Objects.equals(this.consumedOnChainId, utxo.consumedOnChainId) &&
        Objects.equals(this.creationTxHash, utxo.creationTxHash) &&
        Objects.equals(this.consumingTxHash, utxo.consumingTxHash) &&
        Objects.equals(this.consumingTxTimestamp, utxo.consumingTxTimestamp) &&
        Objects.equals(this.outputIndex, utxo.outputIndex) &&
        Objects.equals(this.timestamp, utxo.timestamp) &&
        Objects.equals(this.locktime, utxo.locktime) &&
        Objects.equals(this.threshold, utxo.threshold) &&
        Objects.equals(this.addresses, utxo.addresses) &&
        Objects.equals(this.credentials, utxo.credentials);
  }

  @Override
  public int hashCode() {
    return Objects.hash(utxoId, asset, utxoType, createdOnChainId, consumedOnChainId, creationTxHash, consumingTxHash, consumingTxTimestamp, outputIndex, timestamp, locktime, threshold, addresses, credentials);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Utxo {\n");
    
    sb.append("    utxoId: ").append(toIndentedString(utxoId)).append("\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    utxoType: ").append(toIndentedString(utxoType)).append("\n");
    sb.append("    createdOnChainId: ").append(toIndentedString(createdOnChainId)).append("\n");
    sb.append("    consumedOnChainId: ").append(toIndentedString(consumedOnChainId)).append("\n");
    sb.append("    creationTxHash: ").append(toIndentedString(creationTxHash)).append("\n");
    sb.append("    consumingTxHash: ").append(toIndentedString(consumingTxHash)).append("\n");
    sb.append("    consumingTxTimestamp: ").append(toIndentedString(consumingTxTimestamp)).append("\n");
    sb.append("    outputIndex: ").append(toIndentedString(outputIndex)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    locktime: ").append(toIndentedString(locktime)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    credentials: ").append(toIndentedString(credentials)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
