/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * XChainSharedAssetBalance
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class XChainSharedAssetBalance {
  @SerializedName("assetId")
  private String assetId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("denomination")
  private BigDecimal denomination = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("amount")
  private String amount = null;

  @SerializedName("utxoCount")
  private BigDecimal utxoCount = null;

  @SerializedName("sharedWithChainId")
  private String sharedWithChainId = null;

  public XChainSharedAssetBalance assetId(String assetId) {
    this.assetId = assetId;
    return this;
  }

   /**
   * Unique ID for an asset.
   * @return assetId
  **/
  @Schema(example = "th5aLdWLi32yS9ED6uLGoMMubqHjzMsXhKWwzP6yZTYQKYzof", required = true, description = "Unique ID for an asset.")
  public String getAssetId() {
    return assetId;
  }

  public void setAssetId(String assetId) {
    this.assetId = assetId;
  }

  public XChainSharedAssetBalance name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of this asset.
   * @return name
  **/
  @Schema(example = "Avalanche", required = true, description = "Name of this asset.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public XChainSharedAssetBalance symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Symbol for this asset (max 4 characters).
   * @return symbol
  **/
  @Schema(example = "AVAX", required = true, description = "Symbol for this asset (max 4 characters).")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public XChainSharedAssetBalance denomination(BigDecimal denomination) {
    this.denomination = denomination;
    return this;
  }

   /**
   * Denomination of this asset to represent fungibility.
   * @return denomination
  **/
  @Schema(example = "9", required = true, description = "Denomination of this asset to represent fungibility.")
  public BigDecimal getDenomination() {
    return denomination;
  }

  public void setDenomination(BigDecimal denomination) {
    this.denomination = denomination;
  }

  public XChainSharedAssetBalance type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of asset like SECP256K1 or NFT.
   * @return type
  **/
  @Schema(example = "secp256k1", required = true, description = "Type of asset like SECP256K1 or NFT.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public XChainSharedAssetBalance amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Amount of the asset.
   * @return amount
  **/
  @Schema(example = "5001000", required = true, description = "Amount of the asset.")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public XChainSharedAssetBalance utxoCount(BigDecimal utxoCount) {
    this.utxoCount = utxoCount;
    return this;
  }

   /**
   * Get utxoCount
   * @return utxoCount
  **/
  @Schema(required = true, description = "")
  public BigDecimal getUtxoCount() {
    return utxoCount;
  }

  public void setUtxoCount(BigDecimal utxoCount) {
    this.utxoCount = utxoCount;
  }

  public XChainSharedAssetBalance sharedWithChainId(String sharedWithChainId) {
    this.sharedWithChainId = sharedWithChainId;
    return this;
  }

   /**
   * Get sharedWithChainId
   * @return sharedWithChainId
  **/
  @Schema(required = true, description = "")
  public String getSharedWithChainId() {
    return sharedWithChainId;
  }

  public void setSharedWithChainId(String sharedWithChainId) {
    this.sharedWithChainId = sharedWithChainId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XChainSharedAssetBalance xchainSharedAssetBalance = (XChainSharedAssetBalance) o;
    return Objects.equals(this.assetId, xchainSharedAssetBalance.assetId) &&
        Objects.equals(this.name, xchainSharedAssetBalance.name) &&
        Objects.equals(this.symbol, xchainSharedAssetBalance.symbol) &&
        Objects.equals(this.denomination, xchainSharedAssetBalance.denomination) &&
        Objects.equals(this.type, xchainSharedAssetBalance.type) &&
        Objects.equals(this.amount, xchainSharedAssetBalance.amount) &&
        Objects.equals(this.utxoCount, xchainSharedAssetBalance.utxoCount) &&
        Objects.equals(this.sharedWithChainId, xchainSharedAssetBalance.sharedWithChainId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetId, name, symbol, denomination, type, amount, utxoCount, sharedWithChainId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XChainSharedAssetBalance {\n");
    
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    denomination: ").append(toIndentedString(denomination)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    utxoCount: ").append(toIndentedString(utxoCount)).append("\n");
    sb.append("    sharedWithChainId: ").append(toIndentedString(sharedWithChainId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
