/*
 * Glacier API
 * The Glacier API provides web3 application developers with multi-chain        data related to Avalanche's primary network, Avalanche subnets, and        Ethereum. With Glacier, you can easily build products that leverage        real-time and historical transaction and transfer history, native and        token balances, and various types of token metadata. The API is in Beta        and may be subject to change.        </br></br>        If you have feedback or feature requests for the API, please submit them        <a href=\"https://portal.productboard.com/dndv9ahlkdfye4opdm8ksafi/tabs/4-glacier-api\">here</a>. Bug reports can be submitted        <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeJQrcp7QoNiqozMDKrVJGX5wpU827d3cVTgF8qa7t_J1Pb-g/viewform\">here</a>, and any potential security        issues can be reported <a href=\"https://hackenproof.com/avalanche\">here</a>.
 *
 * OpenAPI spec version: Beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * XChainAssetDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-05-05T19:37:42.090584799-03:00[America/Sao_Paulo]")
public class XChainAssetDetails {
  @SerializedName("assetId")
  private String assetId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("denomination")
  private BigDecimal denomination = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("createdAtTimestamp")
  private BigDecimal createdAtTimestamp = null;

  @SerializedName("cap")
  private String cap = null;

  public XChainAssetDetails assetId(String assetId) {
    this.assetId = assetId;
    return this;
  }

   /**
   * Unique ID for an asset.
   * @return assetId
  **/
  @Schema(example = "th5aLdWLi32yS9ED6uLGoMMubqHjzMsXhKWwzP6yZTYQKYzof", required = true, description = "Unique ID for an asset.")
  public String getAssetId() {
    return assetId;
  }

  public void setAssetId(String assetId) {
    this.assetId = assetId;
  }

  public XChainAssetDetails name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of this asset.
   * @return name
  **/
  @Schema(example = "Avalanche", required = true, description = "Name of this asset.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public XChainAssetDetails symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Symbol for this asset (max 4 characters).
   * @return symbol
  **/
  @Schema(example = "AVAX", required = true, description = "Symbol for this asset (max 4 characters).")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public XChainAssetDetails denomination(BigDecimal denomination) {
    this.denomination = denomination;
    return this;
  }

   /**
   * Denomination of this asset to represent fungibility.
   * @return denomination
  **/
  @Schema(example = "9", required = true, description = "Denomination of this asset to represent fungibility.")
  public BigDecimal getDenomination() {
    return denomination;
  }

  public void setDenomination(BigDecimal denomination) {
    this.denomination = denomination;
  }

  public XChainAssetDetails type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of asset like SECP256K1 or NFT.
   * @return type
  **/
  @Schema(example = "secp256k1", required = true, description = "Type of asset like SECP256K1 or NFT.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public XChainAssetDetails createdAtTimestamp(BigDecimal createdAtTimestamp) {
    this.createdAtTimestamp = createdAtTimestamp;
    return this;
  }

   /**
   * Timestamp in seconds this asset was created on.
   * @return createdAtTimestamp
  **/
  @Schema(example = "1675444720", required = true, description = "Timestamp in seconds this asset was created on.")
  public BigDecimal getCreatedAtTimestamp() {
    return createdAtTimestamp;
  }

  public void setCreatedAtTimestamp(BigDecimal createdAtTimestamp) {
    this.createdAtTimestamp = createdAtTimestamp;
  }

  public XChainAssetDetails cap(String cap) {
    this.cap = cap;
    return this;
  }

   /**
   * Cap represents if an asset can be or is fixed cap.
   * @return cap
  **/
  @Schema(example = "fixed", required = true, description = "Cap represents if an asset can be or is fixed cap.")
  public String getCap() {
    return cap;
  }

  public void setCap(String cap) {
    this.cap = cap;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XChainAssetDetails xchainAssetDetails = (XChainAssetDetails) o;
    return Objects.equals(this.assetId, xchainAssetDetails.assetId) &&
        Objects.equals(this.name, xchainAssetDetails.name) &&
        Objects.equals(this.symbol, xchainAssetDetails.symbol) &&
        Objects.equals(this.denomination, xchainAssetDetails.denomination) &&
        Objects.equals(this.type, xchainAssetDetails.type) &&
        Objects.equals(this.createdAtTimestamp, xchainAssetDetails.createdAtTimestamp) &&
        Objects.equals(this.cap, xchainAssetDetails.cap);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetId, name, symbol, denomination, type, createdAtTimestamp, cap);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XChainAssetDetails {\n");
    
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    denomination: ").append(toIndentedString(denomination)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    createdAtTimestamp: ").append(toIndentedString(createdAtTimestamp)).append("\n");
    sb.append("    cap: ").append(toIndentedString(cap)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
